# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhgHi-KSyuSlOzJYd7ituevRZKoAmSRm
"""

# CELLA 1 — Setup Kaggle con token diretto
import os, json

# Incolla qui i tuoi valori
KAGGLE_USERNAME = "totana95"
KAGGLE_KEY = "KGAT_61893ce79a2e7c7982c7b24936c92bc0"

# Crea il file kaggle.json automaticamente
os.makedirs('/root/.kaggle', exist_ok=True)
with open('/root/.kaggle/kaggle.json', 'w') as f:
    json.dump({"username": KAGGLE_USERNAME, "key": KAGGLE_KEY}, f)
os.chmod('/root/.kaggle/kaggle.json', 0o600)

# Scarica i dataset
!kaggle datasets download -d martj42/international-football-results-from-1872-to-2017 --unzip
!kaggle datasets download -d cashncarry/fifaworldranking --unzip

print("✅ Dataset pronti!")
print([f for f in os.listdir('.') if f.endswith('.csv')])

# CELLA 2 — Caricamento e ispezione dataset
import pandas as pd
import numpy as np

# Carichiamo tutto
risultati = pd.read_csv('results.csv')
shootouts = pd.read_csv('shootouts.csv')
goalscorers = pd.read_csv('goalscorers.csv')
ranking = pd.read_csv('fifa_ranking-2024-06-20.csv')  # usiamo il più recente

# Convertiamo le date
risultati['date'] = pd.to_datetime(risultati['date'])
shootouts['date'] = pd.to_datetime(shootouts['date'])
goalscorers['date'] = pd.to_datetime(goalscorers['date'])
ranking['rank_date'] = pd.to_datetime(ranking['rank_date'])

# Ispezione rapida
print("=== RISULTATI ===")
print(f"Righe: {len(risultati)} | Da: {risultati['date'].min()} a: {risultati['date'].max()}")
print(risultati.columns.tolist())
print(risultati.head(3))

print("\n=== RANKING FIFA ===")
print(f"Righe: {len(ranking)}")
print(ranking.columns.tolist())
print(ranking.head(3))

print("\n=== SHOOTOUTS ===")
print(f"Righe: {len(shootouts)}")
print(shootouts.head(3))

print("\n=== TORNEI DISPONIBILI (top 20) ===")
print(risultati['tournament'].value_counts().head(20))

# CELLA 3 — Feature Engineering (senza data leakage)
import pandas as pd
import numpy as np
from functools import lru_cache

# ── 1. FILTRO: solo dal 2010 e partite "serie" ──────────────────
TORNEI_PESO = {
    'FIFA World Cup': 5,
    'FIFA World Cup qualification': 3,
    'UEFA Euro': 4,
    'Copa América': 4,
    'African Cup of Nations': 4,
    'AFC Asian Cup': 4,
    'Gold Cup': 3,
    'UEFA Euro qualification': 2,
    'African Cup of Nations qualification': 2,
    'AFC Asian Cup qualification': 2,
    'UEFA Nations League': 2,
    'CONCACAF Nations League': 2,
    'Friendly': 1,
}

df = risultati[risultati['date'] >= '2010-01-01'].copy()
df['tournament_weight'] = df['tournament'].map(TORNEI_PESO).fillna(1)

# ── 2. RANKING FIFA STORICO (senza data leakage) ─────────────────
# Per ogni partita usiamo il rank più recente PRIMA della data
ranking_sorted = ranking.sort_values('rank_date')

def get_rank_at_date(team, date):
    mask = (ranking_sorted['country_full'] == team) & (ranking_sorted['rank_date'] <= date)
    rows = ranking_sorted[mask]
    if not rows.empty:
        return rows.iloc[-1]['rank'], rows.iloc[-1]['total_points']
    return 100, 500  # default se non trovato

# ── 3. FORMA RECENTE ─────────────────────────────────────────────
# Punti, gol fatti, gol subiti negli ultimi N match pesati per importanza torneo
def forma_squadra(team, date, n=10):
    partite = df[
        ((df['home_team'] == team) | (df['away_team'] == team)) &
        (df['date'] < date)
    ].tail(n)

    if partite.empty:
        return 0, 0, 0, 0  # punti, gol_fatti, gol_subiti, partite_giocate

    punti_tot = 0
    gol_fatti = 0
    gol_subiti = 0
    peso_tot = 0

    for _, r in partite.iterrows():
        peso = r['tournament_weight']
        if r['home_team'] == team:
            gf, gs = r['home_score'], r['away_score']
        else:
            gf, gs = r['away_score'], r['home_score']

        gol_fatti += gf * peso
        gol_subiti += gs * peso
        peso_tot += peso

        if gf > gs:
            punti_tot += 3 * peso
        elif gf == gs:
            punti_tot += 1 * peso

    n_partite = len(partite)
    return (
        punti_tot / peso_tot if peso_tot > 0 else 0,
        gol_fatti / peso_tot if peso_tot > 0 else 0,
        gol_subiti / peso_tot if peso_tot > 0 else 0,
        n_partite
    )

# ── 4. HEAD TO HEAD ──────────────────────────────────────────────
def head_to_head(team_a, team_b, date, n=10):
    scontri = df[
        (
            ((df['home_team'] == team_a) & (df['away_team'] == team_b)) |
            ((df['home_team'] == team_b) & (df['away_team'] == team_a))
        ) &
        (df['date'] < date)
    ].tail(n)

    if scontri.empty:
        return 0, 0, 0  # vittorie_a, pareggi, vittorie_b

    v_a, par, v_b = 0, 0, 0
    for _, r in scontri.iterrows():
        if r['home_team'] == team_a:
            hs, as_ = r['home_score'], r['away_score']
        else:
            hs, as_ = r['away_score'], r['home_score']

        if hs > as_: v_a += 1
        elif hs == as_: par += 1
        else: v_b += 1

    tot = len(scontri)
    return v_a/tot, par/tot, v_b/tot

# ── 5. COSTRUZIONE DATASET FEATURE ───────────────────────────────
print("Costruendo feature dataset... (può richiedere 2-3 minuti)")

records = []
for _, row in df.iterrows():
    date = row['date']
    home = row['home_team']
    away = row['away_team']

    # Skip se score mancante
    if pd.isna(row['home_score']) or pd.isna(row['away_score']):
        continue

    # Rank FIFA alla data
    rank_h, pts_h = get_rank_at_date(home, date)
    rank_a, pts_a = get_rank_at_date(away, date)

    # Forma recente
    punti_h, gf_h, gs_h, n_h = forma_squadra(home, date)
    punti_a, gf_a, gs_a, n_a = forma_squadra(away, date)

    # Head to head
    h2h_h, h2h_par, h2h_a = head_to_head(home, away, date)

    # Target
    if row['home_score'] > row['away_score']:
        target = 0  # vittoria casa
    elif row['home_score'] == row['away_score']:
        target = 1  # pareggio
    else:
        target = 2  # vittoria trasferta

    records.append({
        'date': date,
        'home_team': home,
        'away_team': away,
        'home_score': row['home_score'],
        'away_score': row['away_score'],
        'tournament': row['tournament'],
        'tournament_weight': row['tournament_weight'],
        'neutral': int(row['neutral']),
        # Rank features
        'rank_home': rank_h,
        'rank_away': rank_a,
        'diff_rank': rank_h - rank_a,
        'pts_home': pts_h,
        'pts_away': pts_a,
        'diff_pts': pts_h - pts_a,
        # Forma
        'forma_punti_home': punti_h,
        'forma_punti_away': punti_a,
        'diff_forma': punti_h - punti_a,
        'gol_fatti_home': gf_h,
        'gol_fatti_away': gf_a,
        'gol_subiti_home': gs_h,
        'gol_subiti_away': gs_a,
        # H2H
        'h2h_home': h2h_h,
        'h2h_away': h2h_a,
        'h2h_par': h2h_par,
        # Target
        'risultato': target,
    })

features_df = pd.DataFrame(records)
print(f"✅ Dataset feature pronto: {len(features_df)} partite")
print(f"Distribuzione risultati:\n{features_df['risultato'].value_counts(normalize=True).round(3)}")
features_df.to_csv('features_mondiale.csv', index=False)
print("\nSample:")
print(features_df[['date','home_team','away_team','diff_rank','diff_forma','h2h_home','risultato']].head(5))

# CELLA 4 — Training XGBoost + Calibrazione + Valutazione
import xgboost as xgb
from sklearn.calibration import CalibratedClassifierCV
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import accuracy_score, classification_report, log_loss
import matplotlib.pyplot as plt

# ── 1. FEATURE E TARGET ──────────────────────────────────────────
FEATURE_COLS = [
    'diff_rank', 'diff_pts',
    'forma_punti_home', 'forma_punti_away', 'diff_forma',
    'gol_fatti_home', 'gol_fatti_away',
    'gol_subiti_home', 'gol_subiti_away',
    'h2h_home', 'h2h_away', 'h2h_par',
    'neutral', 'tournament_weight',
    'rank_home', 'rank_away',
]

# Ordine temporale — fondamentale per TimeSeriesSplit
features_df = features_df.sort_values('date').reset_index(drop=True)

X = features_df[FEATURE_COLS].fillna(0)
y = features_df['risultato']

# ── 2. SPLIT TEMPORALE (non random!) ────────────────────────────
# Usiamo gli ultimi 20% come test set (partite più recenti)
split_idx = int(len(X) * 0.8)
X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

print(f"Train: {len(X_train)} partite | Test: {len(X_test)} partite")
print(f"Test dal: {features_df.iloc[split_idx]['date'].date()}")

# ── 3. MODELLO XGBOOST ───────────────────────────────────────────
xgb_model = xgb.XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    use_label_encoder=False,
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1
)

# ── 4. CALIBRAZIONE PROBABILITÀ ──────────────────────────────────
# Senza calibrazione le predict_proba di XGBoost sono spesso sbagliate
modello_calibrato = CalibratedClassifierCV(
    xgb_model,
    method='isotonic',  # più flessibile di 'sigmoid'
    cv=5
)

print("\nTraining in corso...")
modello_calibrato.fit(X_train, y_train)
print("✅ Modello addestrato e calibrato!")

# ── 5. VALUTAZIONE ───────────────────────────────────────────────
y_pred = modello_calibrato.predict(X_test)
y_proba = modello_calibrato.predict_proba(X_test)

acc = accuracy_score(y_test, y_pred)
ll = log_loss(y_test, y_proba)

print(f"\n📊 RISULTATI SUL TEST SET")
print(f"Accuratezza: {acc:.2%}")
print(f"Log Loss: {ll:.4f} (più basso = meglio, random baseline ≈ 1.09)")
print(f"\n{classification_report(y_test, y_pred, target_names=['Vittoria Casa', 'Pareggio', 'Vittoria Trasferta'])}")

# ── 6. FEATURE IMPORTANCE ────────────────────────────────────────
# Estraiamo dall'estimatore base dentro il calibrato
base_model = modello_calibrato.calibrated_classifiers_[0].estimator
importances = pd.Series(base_model.feature_importances_, index=FEATURE_COLS)
importances.sort_values().plot(kind='barh', figsize=(8, 6), title='Feature Importance')
plt.tight_layout()
plt.show()

# CELLA 4b — Fix pareggi con class weights
from sklearn.utils.class_weight import compute_sample_weight

# Calcoliamo pesi per bilanciare le classi
sample_weights = compute_sample_weight(class_weight='balanced', y=y_train)

xgb_model2 = xgb.XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1
)

modello_calibrato2 = CalibratedClassifierCV(xgb_model2, method='isotonic', cv=5)

# Passiamo i pesi durante il fit
print("Training con class weights...")
modello_calibrato2.fit(X_train, y_train, sample_weight=sample_weights)

y_pred2 = modello_calibrato2.predict(X_test)
y_proba2 = modello_calibrato2.predict_proba(X_test)

acc2 = accuracy_score(y_test, y_pred2)
ll2 = log_loss(y_test, y_proba2)

print(f"Accuratezza: {acc2:.2%} (prima: 58.62%)")
print(f"Log Loss: {ll2:.4f} (prima: 0.9161)")
print(f"\n{classification_report(y_test, y_pred2, target_names=['Vittoria Casa', 'Pareggio', 'Vittoria Trasferta'])}")

# Scegliamo il modello migliore per log loss (più importante dell'accuratezza per le probabilità)
if ll2 < 0.9161:
    modello_finale = modello_calibrato2
    print("\n✅ Usiamo il modello con class weights")
else:
    modello_finale = modello_calibrato
    print("\n✅ Usiamo il modello originale (migliore log loss)")

# CELLA 4c — Separazione partite giocate vs da giocare
from datetime import datetime

# Data di oggi
OGGI = pd.Timestamp('2026-06-15')

# Filtriamo solo le partite dei Mondiali 2026 dal dataset
mondiali_2026 = risultati[
    (risultati['tournament'] == 'FIFA World Cup') &
    (risultati['date'] >= '2026-06-01')
].copy()

mondiali_giocate = mondiali_2026[mondiali_2026['date'] <= OGGI].copy()
mondiali_future = mondiali_2026[mondiali_2026['date'] > OGGI].copy()

print(f"Partite Mondiali 2026 già giocate: {len(mondiali_giocate)}")
print(f"Partite Mondiali 2026 ancora da giocare: {len(mondiali_future)}")

print("\n=== GIÀ GIOCATE ===")
cols = ['date', 'home_team', 'away_team', 'home_score', 'away_score']
print(mondiali_giocate[cols].to_string(index=False))

print("\n=== DA GIOCARE ===")
print(mondiali_future[cols].to_string(index=False))

# CELLA 4d — Soglia custom per pareggi + modello finale
import numpy as np

# Usiamo modello originale (log loss migliore)
modello_finale = modello_calibrato

# Le probabilità grezze
y_proba_final = modello_finale.predict_proba(X_test)

# Soglia custom: se prob pareggio > 0.27 → predici pareggio
# (invece della soglia default 0.33 che lo ignora quasi sempre)
SOGLIA_PAREGGIO = 0.27

def predici_con_soglia(proba, soglia_par=SOGLIA_PAREGGIO):
    risultati = []
    for p in proba:
        p_casa, p_par, p_trasf = p[0], p[1], p[2]
        if p_par >= soglia_par:
            risultati.append(1)
        else:
            risultati.append(np.argmax([p_casa, p_par, p_trasf]))
    return np.array(risultati)

y_pred_custom = predici_con_soglia(y_proba_final)

acc_custom = accuracy_score(y_test, y_pred_custom)
ll_custom = log_loss(y_test, y_proba_final)  # log loss non cambia, dipende solo dalle prob

print(f"Accuratezza con soglia custom: {acc_custom:.2%}")
print(f"Log Loss: {ll_custom:.4f}")
print(f"\n{classification_report(y_test, y_pred_custom, target_names=['Vittoria Casa', 'Pareggio', 'Vittoria Trasferta'])}")

# Funzione oracolo finale
def oracolo(squadra_casa, squadra_trasferta, neutro=True):
    r_casa, pts_casa = get_rank_at_date(squadra_casa, pd.Timestamp.now())
    r_trasf, pts_trasf = get_rank_at_date(squadra_trasferta, pd.Timestamp.now())

    p_casa, gf_casa, gs_casa, _ = forma_squadra(squadra_casa, pd.Timestamp.now())
    p_trasf, gf_trasf, gs_trasf, _ = forma_squadra(squadra_trasferta, pd.Timestamp.now())

    h2h_h, h2h_par, h2h_a = head_to_head(squadra_casa, squadra_trasferta, pd.Timestamp.now())

    match = pd.DataFrame([{
        'diff_rank': r_casa - r_trasf,
        'diff_pts': pts_casa - pts_trasf,
        'forma_punti_home': p_casa,
        'forma_punti_away': p_trasf,
        'diff_forma': p_casa - p_trasf,
        'gol_fatti_home': gf_casa,
        'gol_fatti_away': gf_trasf,
        'gol_subiti_home': gs_casa,
        'gol_subiti_away': gs_trasf,
        'h2h_home': h2h_h,
        'h2h_away': h2h_a,
        'h2h_par': h2h_par,
        'neutral': int(neutro),
        'tournament_weight': 5,  # Mondiali
        'rank_home': r_casa,
        'rank_away': r_trasf,
    }])

    proba = modello_finale.predict_proba(match)[0]
    pred = predici_con_soglia([proba])[0]
    nomi = {0: f'Vittoria {squadra_casa}', 1: 'Pareggio', 2: f'Vittoria {squadra_trasferta}'}

    print(f"\n⚽ {squadra_casa} vs {squadra_trasferta}")
    print(f"  {squadra_casa}: {proba[0]:.1%}")
    print(f"  Pareggio:      {proba[1]:.1%}")
    print(f"  {squadra_trasferta}: {proba[2]:.1%}")
    print(f"  → Esito: {nomi[pred]}")

    return {'home': squadra_casa, 'away': squadra_trasferta,
            'prob_home': round(proba[0], 3), 'prob_draw': round(proba[1], 3),
            'prob_away': round(proba[2], 3), 'prediction': pred}

# Test
oracolo("Brazil", "Argentina")
oracolo("Italy", "France")
oracolo("Germany", "Spain")

# CELLA 5 — Gironi Mondiali 2026 + Export JSON
import json
import itertools
from datetime import datetime

# ── 1. GIRONI UFFICIALI 2026 ─────────────────────────────────────
GIRONI = {
    'A': ['Mexico', 'South Korea', 'South Africa', 'Czech Republic'],
    'B': ['Canada', 'Switzerland', 'Qatar', 'Bosnia and Herzegovina'],
    'C': ['Brazil', 'Morocco', 'Haiti', 'Scotland'],
    'D': ['United States', 'Paraguay', 'Australia', 'Turkey'],
    'E': ['Germany', 'Ecuador', 'Ivory Coast', 'Curacao'],
    'F': ['Netherlands', 'Japan', 'Tunisia', 'Sweden'],
    'G': ['Belgium', 'Egypt', 'Iran', 'New Zealand'],
    'H': ['Spain', 'Uruguay', 'Saudi Arabia', 'Cape Verde'],
    'I': ['France', 'Senegal', 'Norway', 'Iraq'],
    'J': ['Argentina', 'Algeria', 'Austria', 'Jordan'],
    'K': ['Portugal', 'Colombia', 'Uzbekistan', 'DR Congo'],
    'L': ['England', 'Croatia', 'Ghana', 'Panama'],
}

# ── 2. PARTITE GIÀ GIOCATE DAL DATASET ──────────────────────────
mondiali_reali = risultati[
    (risultati['tournament'] == 'FIFA World Cup') &
    (risultati['date'] >= '2026-06-01')
].copy()

# Dizionario lookup risultati reali: (home, away) -> {score, result}
risultati_reali = {}
for _, r in mondiali_reali.iterrows():
    key = (r['home_team'], r['away_team'])
    risultati_reali[key] = {
        'home_score': int(r['home_score']) if not pd.isna(r['home_score']) else None,
        'away_score': int(r['away_score']) if not pd.isna(r['away_score']) else None,
        'played': True,
        'date': r['date'].strftime('%Y-%m-%d')
    }

print(f"Partite reali trovate nel dataset: {len(risultati_reali)}")
for k, v in risultati_reali.items():
    print(f"  {k[0]} {v['home_score']}-{v['away_score']} {k[1]}")

# ── 3. CALCOLA TUTTE LE PARTITE DEI GIRONI ───────────────────────
# Fix nella funzione calcola_girone — sostituisci il controllo reale con questo:

def calcola_girone(lettera, squadre):
    partite = []
    for home, away in itertools.combinations(squadre, 2):
        reale_key = None
        reale = None
        invertita = False

        if (home, away) in risultati_reali:
            reale_key = (home, away)
        elif (away, home) in risultati_reali:
            reale_key = (away, home)
            invertita = True

        if reale_key:
            r = risultati_reali[reale_key]
            # Solo se i punteggi sono reali (non None)
            if r['home_score'] is not None and r['away_score'] is not None:
                if invertita:
                    hs, as_ = r['away_score'], r['home_score']
                else:
                    hs, as_ = r['home_score'], r['away_score']

                partite.append({
                    'home': home, 'away': away,
                    'status': 'played',
                    'home_score': hs, 'away_score': as_,
                    'prob_home': None, 'prob_draw': None, 'prob_away': None,
                    'prediction': None,
                })
                continue  # salta alla prossima partita

        # Se non giocata (o score None) → predizione AI
        try:
            pred = oracolo(home, away, neutro=True)
            partite.append({
                'home': home, 'away': away,
                'status': 'predicted',
                'home_score': None, 'away_score': None,
                'prob_home': float(pred['prob_home']),
                'prob_draw': float(pred['prob_draw']),
                'prob_away': float(pred['prob_away']),
                'prediction': int(pred['prediction']),
            })
        except Exception as e:
            print(f"  ⚠️ Errore {home} vs {away}: {e}")
            partite.append({
                'home': home, 'away': away, 'status': 'error',
                'home_score': None, 'away_score': None,
                'prob_home': 0.33, 'prob_draw': 0.33, 'prob_away': 0.34,
                'prediction': 1,
            })
    return partite
# ── 4. CLASSIFICA GIRONE ─────────────────────────────────────────
def calcola_classifica(squadre, partite):
    classifica = {s: {'punti': 0, 'gf': 0, 'gs': 0, 'pg': 0} for s in squadre}

    for p in partite:
        if p['status'] != 'played':
            # Usa predizione per classifica proiettata
            prob_h = p['prob_home'] or 0.33
            prob_d = p['prob_draw'] or 0.33
            prob_a = p['prob_away'] or 0.34
            pred = p['prediction'] if p['prediction'] is not None else 0

            if pred == 0:
                classifica[p['home']]['punti'] += 3
            elif pred == 1:
                classifica[p['home']]['punti'] += 1
                classifica[p['away']]['punti'] += 1
            else:
                classifica[p['away']]['punti'] += 3
            classifica[p['home']]['pg'] += 1
            classifica[p['away']]['pg'] += 1
        else:
            hs, as_ = p['home_score'], p['away_score']
            classifica[p['home']]['gf'] += hs
            classifica[p['home']]['gs'] += as_
            classifica[p['away']]['gf'] += as_
            classifica[p['away']]['gs'] += hs
            classifica[p['home']]['pg'] += 1
            classifica[p['away']]['pg'] += 1
            if hs > as_:
                classifica[p['home']]['punti'] += 3
            elif hs == as_:
                classifica[p['home']]['punti'] += 1
                classifica[p['away']]['punti'] += 1
            else:
                classifica[p['away']]['punti'] += 3

    return sorted(classifica.items(), key=lambda x: (-x[1]['punti'], -(x[1]['gf']-x[1]['gs'])))

# ── 5. GENERA TUTTO ──────────────────────────────────────────────
print("\nGenerando predizioni per tutti i gironi...")
output = {
    'generated_at': datetime.now().strftime('%Y-%m-%d %H:%M'),
    'model_accuracy': '54%',
    'model_logloss': '0.9161',
    'groups': {}
}

for lettera, squadre in GIRONI.items():
    print(f"  Girone {lettera}...")
    partite = calcola_girone(lettera, squadre)
    classifica = calcola_classifica(squadre, partite)

    output['groups'][lettera] = {
        'teams': squadre,
        'matches': partite,
        'standings': [
            {
                'team': team,
                'points': stats['punti'],
                'played': stats['pg'],
                'gf': stats['gf'],
                'gs': stats['gs'],
                'advances': idx < 2  # prime 2 passano
            }
            for idx, (team, stats) in enumerate(classifica)
        ]
    }

# ── 6. EXPORT JSON ───────────────────────────────────────────────
with open('predictions.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print("\n✅ predictions.json generato!")
print(f"Totale partite: {sum(len(g['matches']) for g in output['groups'].values())}")
print(f"\nClassifica Girone A (preview):")
for entry in output['groups']['A']['standings']:
    adv = "✅" if entry['advances'] else "❌"
    print(f"  {adv} {entry['team']}: {entry['points']} pt")

# CELLA 7b — Pre-cache feature squadre + Monte Carlo veloce
import random
from functools import lru_cache

print("Pre-calcolo feature squadre...")

# Tutte le squadre del torneo
TUTTE_SQUADRE = [s for squadre in GIRONI.values() for s in squadre]
NOW = pd.Timestamp.now()

# Cache: calcola rank, forma, una volta sola per squadra
squad_cache = {}
for team in TUTTE_SQUADRE:
    rank, pts = get_rank_at_date(team, NOW)
    punti_f, gf, gs, _ = forma_squadra(team, NOW)
    squad_cache[team] = {
        'rank': rank, 'pts': pts,
        'forma': punti_f, 'gf': gf, 'gs': gs
    }
    print(f"  {team}: rank={rank}, forma={punti_f:.1f}")

print("✅ Cache pronta!")

# ── PREDIZIONE VELOCE (usa cache) ───────────────────────────────
def prob_partita(team_a, team_b):
    a = squad_cache.get(team_a, {'rank':100,'pts':500,'forma':0,'gf':0,'gs':0})
    b = squad_cache.get(team_b, {'rank':100,'pts':500,'forma':0,'gf':0,'gs':0})
    h2h_a, h2h_par, h2h_b = head_to_head(team_a, team_b, NOW)

    match = pd.DataFrame([{
        'diff_rank': a['rank'] - b['rank'],
        'diff_pts': a['pts'] - b['pts'],
        'forma_punti_home': a['forma'],
        'forma_punti_away': b['forma'],
        'diff_forma': a['forma'] - b['forma'],
        'gol_fatti_home': a['gf'], 'gol_fatti_away': b['gf'],
        'gol_subiti_home': a['gs'], 'gol_subiti_away': b['gs'],
        'h2h_home': h2h_a, 'h2h_away': h2h_b, 'h2h_par': h2h_par,
        'neutral': 1, 'tournament_weight': 5,
        'rank_home': a['rank'], 'rank_away': b['rank'],
    }])
    return modello_finale.predict_proba(match)[0]  # [p_home, p_draw, p_away]

# Pre-cache anche i prob H2H per tutte le coppie del torneo
print("\nPre-calcolo probabilità per tutte le coppie...")
prob_cache = {}
for i, t1 in enumerate(TUTTE_SQUADRE):
    for t2 in TUTTE_SQUADRE[i+1:]:
        p = prob_partita(t1, t2)
        prob_cache[(t1, t2)] = p
        prob_cache[(t2, t1)] = [p[2], p[1], p[0]]  # inverti home/away

print(f"✅ {len(prob_cache)} coppie pre-calcolate!")

# ── SIMULAZIONE VELOCE ──────────────────────────────────────────
def simula_ko(team_a, team_b):
    """Vincitore K.O. — nessuna chiamata al modello, usa cache"""
    key = (team_a, team_b)
    if key in prob_cache:
        p = prob_cache[key]
    else:
        p = [0.33, 0.33, 0.34]
    r = random.random()
    if r < p[0]: return team_a
    elif r < p[0] + p[1]: return team_a if random.random() < 0.5 else team_b
    else: return team_b

def simula_girone_fast(squadre):
    """Simula girone usando prob_cache, restituisce classifica"""
    cls = {s: {'pt':0,'gf':0,'gs':0} for s in squadre}

    for home, away in itertools.combinations(squadre, 2):
        # Usa risultato reale se disponibile
        reale = risultati_reali.get((home, away)) or risultati_reali.get((away, home))
        if reale and reale['home_score'] is not None:
            inv = risultati_reali.get((away, home))
            hs = reale['away_score'] if inv else reale['home_score']
            as_ = reale['home_score'] if inv else reale['away_score']
        else:
            # Simula stocasticamente
            key = (home, away)
            p = prob_cache.get(key, [0.33, 0.33, 0.34])
            r = random.random()
            if r < p[0]: hs, as_ = 2, 0
            elif r < p[0]+p[1]: hs, as_ = 1, 1
            else: hs, as_ = 0, 2

        cls[home]['gf'] += hs; cls[home]['gs'] += as_
        cls[away]['gf'] += as_; cls[away]['gs'] += hs
        if hs > as_: cls[home]['pt'] += 3
        elif hs == as_: cls[home]['pt'] += 1; cls[away]['pt'] += 1
        else: cls[away]['pt'] += 3

    return sorted(cls.items(), key=lambda x: (-x[1]['pt'], -(x[1]['gf']-x[1]['gs']), -x[1]['gf']))

def simula_torneo_fast():
    # 1. Gironi
    primi, secondi, terze_list = [], [], []
    for g, squadre in GIRONI.items():
        cls = simula_girone_fast(squadre)
        primi.append(cls[0][0])
        secondi.append(cls[1][0])
        terze_list.append((cls[2][0], cls[2][1]['pt']))

    # 2. Migliori 8 terze
    terze_ok = [t for t,_ in sorted(terze_list, key=lambda x: -x[1])[:8]]

    # 3. Round of 32: 12 primi vs 12 terze + 12 secondi vs altro secondo (semplificato)
    r32 = []
    for i in range(12):
        r32.append((primi[i], terze_ok[i % 8]))
    for i in range(0, 12, 2):
        r32.append((secondi[i], secondi[i+1]))

    # Deduplica e prendi 16
    seen, clean = set(), []
    for a, b in r32:
        k = frozenset([a,b])
        if k not in seen and a != b:
            seen.add(k); clean.append((a,b))
        if len(clean) == 16: break

    # 4. Fasi K.O.
    def fase(partite):
        v = [simula_ko(a,b) for a,b in partite]
        return v, [(v[i],v[i+1]) for i in range(0,len(v)-1,2)]

    v32, q = fase(clean)
    v8, s = fase(q)
    v4, f = fase(s)
    return simula_ko(f[0][0], f[0][1]) if f else v4[0]

# ── LANCIA SIMULAZIONI ──────────────────────────────────────────
N = 10000
print(f"\nLancio {N} simulazioni...")
conteggio = {}

for i in range(N):
    v = simula_torneo_fast()
    conteggio[v] = conteggio.get(v, 0) + 1

odds = {t: round(c/N*100, 1) for t,c in sorted(conteggio.items(), key=lambda x: -x[1])}

print("\n🏆 PROBABILITÀ VINCITORE MONDIALE 2026:")
for i, (t, p) in enumerate(odds.items(), 1):
    if p >= 0.5:
        bar = '█' * int(p/2)
        print(f"  {i:2}. {t:<25} {bar} {p}%")

# Aggiorna JSON
output['world_cup_winner_odds'] = odds
with open('predictions.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print("\n✅ predictions.json aggiornato!")
from google.colab import files
files.download('predictions.json')